version: "3.3"
services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - redis
    links:
      - mongo

  redis:
    image: redis

  mongo:
    image: mongo:latest
    restart: always
    volumes:
     - ./data:/data
    # env_file: .env
    ports:
      - "27017:27017"
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      # - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
